# AppVeyor Config - https://www.appveyor.com/docs/build-configuration/
version: '{build}'
skip_tags: true
clone_depth: 30

# Build Environment - https://www.appveyor.com/docs/build-environment/
environment:
  JAVA_HOME: C:\Program Files\Java\jdk10

# Notifications - https://www.appveyor.com/docs/notifications/
notifications:
  - provider: Email
    to:
      - qThegamEp@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
